name: aoc2023
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/nilshohmann/AdventOfCode2023

environment:
  sdk: ^3.2.0

dependencies:
  path: ^1.8.0
  resource_portable: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
